[project]
name = "retrieve-dspy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cohere>=5.16.1",
    "datasets>=4.0.0",
    "dspy==3.*",
    "hdbscan>=0.8.40",
    "ipykernel>=6.30.1",
    "ir-datasets>=0.5.11",
    "matplotlib>=3.10.5",
    "ruff>=0.12.7",
    "voyageai>=0.3.4",
    "weaviate-client[agents]>=4.16.4",
]
